# Supabase project name used across environments
# project = "LovableCloud"
project_id = "pfcaolibtgvynnwaxvol"

[functions.chess-insights]
verify_jwt = false

[functions.generate-chess-rule]
verify_jwt = false

[functions.tournament-matchmaking]
verify_jwt = true

[functions.report-tournament-match]
verify_jwt = true

[functions.sync-tournaments]
verify_jwt = false
