# Supabase project name used across environments
# project = "LovableCloud"
project_id = "pfcaolibtgvynnwaxvol"

[functions.chess-insights]
verify_jwt = false

[functions.generate-chess-rule]
verify_jwt = false
