# Supabase project name used across environments
# project = "Youaregood"
project_id = "ucaqbhmyutlnitnedowk"

[functions.chess-insights]
verify_jwt = false

[functions.generate-chess-rule]
verify_jwt = false
