# Supabase project name used across environments
# project = "Youaregood"
project_id = "ucaqbhmyutlnitnedowk"

[functions.chess-insights]
verify_jwt = true

[functions.generate-chess-rule]
verify_jwt = true

[functions.tournament-matchmaking]
verify_jwt = true

[functions.report-tournament-match]
verify_jwt = true

[functions.sync-tournaments]
verify_jwt = true
