-- 1. Création de la table pour stocker les règles personnalisées
CREATE TABLE public.custom_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,

    -- Qui a créé la règle
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,

    -- Informations de base de la règle
    name TEXT NOT NULL,
    description TEXT,

    -- Le CŒUR de la règle : le JSON généré par l'IA
    -- (Contient les déclencheurs, actions, pièces, etc.)
    rule_metadata JSONB NOT NULL,

    -- Statut pour modération (par défaut, publié)
    status TEXT DEFAULT 'published' NOT NULL
);

-- 2. Activer la Sécurité au niveau des lignes (Row Level Security)
ALTER TABLE public.custom_rules ENABLE ROW LEVEL SECURITY;

-- 3. Définir les politiques d'accès
-- POLITIQUE : Tout le monde (même non-connecté) peut VOIR les règles publiées.
CREATE POLICY "Allow public read access to published rules"
    ON public.custom_rules FOR SELECT
    USING (status = 'published');

-- POLITIQUE : Seuls les utilisateurs connectés (authentifiés) peuvent CRÉER des règles.
CREATE POLICY "Allow authenticated users to create rules"
    ON public.custom_rules FOR INSERT
    WITH CHECK (auth.role() = 'authenticated' AND user_id = auth.uid());
